module.exports = {
    QUERY_TABLE_TK : 'SELECT * FROM TAIKHOAN ',
    QUERY_TABLE_LC : 'SELECT * FROM LOAICAY ',
    QUERY_TABLE_CC : 'SELECT * FROM CAYCANH ',
    QUERY_TABLE_ND : 'SELECT * FROM NGUOIDUNG ',
    QUERY_TABLE_TTDH : 'SELECT * FROM TTDONHANG ',
    QUERY_TABLE_DH : 'SELECT * FROM DONHANG ',
    QUERY_TABLE_CTDH : 'SELECT * FROM CTDONHANG ',
    QUERY_TABLE_QTC : 'SELECT * FROM QUYENTRUYCAP ',
    QUERY_TABLE_HA : 'SELECT * FROM HINHANH ',

    SELECT_TABLE : 'SELECT * FROM ',
    INSERT_TABLE : 'INSERT INTO ',
}

